spring:
  application:
    name: auth-server

#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
debug: true
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/


#    信道维持时间
ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true

#单个访问请求持续时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000