server:
  port: 9999
  context-path: /uaa

#grant-type authorization_code 的方式
#获取授权码测试地址http://localhost:9999/uaa/oauth/authorize?response_type=code&client_id=acme&redirect_uri=http://www.baidu.com&scope=app
#获取token curl acme:acmesecret@localhost:9999/uaa/oauth/token -d grant_type=authorization_code -d client_id=acme -d redirect_ur i=http://www.baidu.com -d code=tS5eVF -d scope=app

#用户名密码直接获取token的方式
#curl http://acme:acmesecret@localhost:9999/uaa/oauth/token -d grant_type=password -d username=pass -d password=pass -d scope=app
security:
#  user:
#    password: pass
#    name: pass #默认的用户名为user
  oauth2:
    client:
      authorized-grant-types: "implicit,authorization_code,refresh_token,password"
      client-secret: acmesecret
      scopes: "app"
      client-id: acme
      auto-approve-scopes: "app"
    authorization:
      check-token-access: "permitAll()"

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth2db?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update



